name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Type Check
        run: yarn tsc --noEmit

      - name: Build and Create Zip
        run: |
          yarn build
          cp public/extension.zip dist/
        env:
          NODE_ENV: production
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_STORAGE_KEY: ${{ secrets.VITE_STORAGE_KEY }}
          VITE_PUBLIC_PATH: ${{ secrets.VITE_PUBLIC_PATH }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
